[package]
name = "keystatsctl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
keystats-core = { path = "../keystats-core" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
clap = { version = "4", features = ["derive"] }
zbus = { version = "5", features = ["blocking"] }
evdev = "0.13"
